name = "modulo-p/cardano-semaphore"
version = "0.0.0"
compiler = "v1.1.15"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'modulo-p/cardano-semaphore'"

[repository]
user = "modulo-p"
project = "cardano-semaphore"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.1.0"
source = "github"

[[dependencies]]
name = "modulo-p/ak-381"
version = "v0.1.1"
source = "github"

[[dependencies]]
name = "aiken-lang/merkle-patricia-forestry"
version = "v2.0.0"
source = "github"
